### ISSUE TITLE
build a Result

### ISSUE THREAD

**Issue by ConnyOnny** [WaDelma/bob#1]
`bob` is awesome to introduce static checks, but some checks can only be done dynamically (e.g. whether some radius parameter is in some range…). Can you please add the option to build a `Result<Struct,ErrorType>` instead? We could have the struct to be built implement a trait like this:

```rust
trait Validatable<E> {
    fn validate(self) -> Result<Self,E>
}
```

Then bob could just call that function. And for the case where no validation is needed, we can either have a marker trait (e.g. `AlwaysValid`) or just not implementing `Validatable`. Whatever you prefer.

**Comment by WaDelma** [comment]
I always wanted to have custom validation for the builder (Infact I was going to implement it for the `macro_rules` based solution next before doing derive based one).

Your proposed solution with traits doesn't unfortunately work perfectly: There is no way to ask if type implements certain trait in custom derive code. Currently with macros 1.1 custom derives you are handed just opaque text blob of the struct that you annotate and it's your job to parse it (using syn crate).

So while I could add trait for the validation there would need to be attribute to mark that you want to validate too. 

One way of doing it would be to have attribute that contains the validation code as text form, but then you lose highlighting. You could even have per field attribute that includes validation for just that field. And because it's code you could just call function that isn't in text form for validation... Hmm... That could work.

**Comment by ConnyOnny** [comment]
How about a boolean flag combined with the trait approach? If the boolean flag is set, you just run that `validate` function assuming it to be present, and if the type doesn't have it, it's a compile-time error.

**Comment by WaDelma** [comment]
I added attribute that allows adding custom validation function for builder.

**Comment by WaDelma** [comment]
I think this should be resolved if you disagree it can be opened/improved.
